[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
license = "MIT"
license-files = ["LICENSE"]
authors = [
  {name = "Leif"},
]
maintainers = [
  {name = "Leif"},
]
name = "vrbm-ai"
version = "0.0.1"
description = "Smart local AI using Ollama"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.urls]
Documentation = "https://vrbm-AI.github.io/vrbm-ai/"
Repository = "https://github.com/vrbm-AI/vrbm-AI"